package utils;

import net.masterthought.cucumber.Configuration;
import net.masterthought.cucumber.ReportBuilder;
import java.io.File;
import java.util.ArrayList;
import java.util.List;

public class GenerateReport {

    public static void generateCucumberReport() {
        File reportOutputDirectory = new File("target/EnhancedCucumberReport");

        // Load the JSON report file generated by Cucumber
        List<String> jsonFiles = new ArrayList<>();
        jsonFiles.add("target/cucumber.json");

        // Set up the configuration for the report
        Configuration configuration = new Configuration(reportOutputDirectory, "Selenium Cucumber Framework");
        configuration.setBuildNumber("1.0.0");
        configuration.addClassifications("Platform", System.getProperty("os.name"));
        configuration.addClassifications("Browser", "Edge");
        configuration.addClassifications("Java Version", System.getProperty("java.version"));

        // Generate the report using the loaded JSON files and the configuration
        ReportBuilder reportBuilder = new ReportBuilder(jsonFiles, configuration);
        reportBuilder.generateReports();
    }
}
